name: lodash
description: A dart utility library inspired by javascript lodash library.
version: 0.0.1
author: Mehdi Zarepour
homepage: https://github.com/mehdizarepour/lodash_dart
repository: https://github.com/mehdizarepour/lodash_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.8